### ISSUE TITLE
(bug): !npm niepoprawnie pobiera liczbę paczek

### ISSUE THREAD

**Issue by mmiszy** [mmiszy/typeofweb-discord-bot#31]
Komenda `!npm` niepoprawnie pobiera liczbę paczek. Zamiast `data.objects.length` powinna używać zwróconego pola `data.total`.

https://github.com/mmiszy/typeofweb-discord-bot/blob/64bcc8c47f3ae1649c01474b1f3dab165e405866/src/commands/npm.ts#L22

**Comment by mmiszy** [comment]
@Deeadline

**Comment by Deeadline** [comment]
Okej szefie

**Comment by mmiszy** [comment]
Fixed in #33
